"""Planted bugs for .claude/skills/graded-module/scripts/mutate.py."""
MUTATIONS = [
    # Each entry: (description, file, exact text, replacement, check step)
    ("payload not 16-byte aligned (header offset is 8, not 16)",
     "allocator.py",
     "        return off + _HEADER\n",
     "        return off + _WORD\n",
     "1"),
    ("first fit does not skip allocated blocks",
     "allocator.py",
     "            if not allocated and size >= need:\n",
     "            if size >= need:\n",
     "1"),
    ("no splitting: a request consumes the whole free block",
     "allocator.py",
     "        if size - need >= _MIN_BLOCK:\n",
     "        if False:\n",
     "1"),
    ("free() does not coalesce with the next block",
     "allocator.py",
     "        if nxt < self.arena_size - _HEADER and not n_alloc:\n",
     "        if False:\n",
     "2"),
    ("free() does not coalesce with the previous block",
     "allocator.py",
     "        if not p_alloc:\n",
     "        if False:\n",
     "2"),
    ("free(NULL) is not a no-op",
     "allocator.py",
     "        if ptr is None:\n            return\n",
     "        if ptr is None:\n            pass\n",
     "4"),
    ("double free is not detected (no allocated-bit check)",
     "allocator.py",
     "        if not allocated:\n            raise DoubleFree(f\"free of {ptr}: the block is already free (double free?)\")\n",
     "        if False:\n            raise DoubleFree(f\"free of {ptr}: the block is already free (double free?)\")\n",
     "4"),
    ("coalesce with the next block even when it is allocated",
     "allocator.py",
     "        if nxt < self.arena_size - _HEADER and not n_alloc:\n",
     "        if nxt < self.arena_size - _HEADER:\n",
     "5"),
]
