"""Planted bugs for .claude/skills/graded-module/scripts/mutate.py."""
MUTATIONS = [
 ("evict without write-back", "pager.py", "                self._write_to_disk(victim, bytes(data))  # write back before dropping\n", "", "2"),
 ("split by count", "btree.py", "            i = _split_point([4 + len(k) + len(v) for k, v in entries])", "            i = len(entries) // 2", "6"),
 ("no CRC check", "wal.py", "        if zlib.crc32(payload) != crc:\n            return  # corrupt or torn inside the payload\n", "", "7"),
 ("replay uncommitted", "wal.py", "        elif kind == \"commit\":\n            out.extend(pending.pop(tx, []))", "        elif kind == \"commit\":\n            pass\n    for ops in pending.values():\n        out.extend(ops)\n    if False:\n        pass", "9"),
 ("no first-committer-wins", "mvcc.py", "                if s._last_commit_ts(key) > self.start_ts:\n                    self._finish(\"aborted\")\n                    raise SerializationFailure(f\"write-write", "                if False:\n                    self._finish(\"aborted\")\n                    raise SerializationFailure(f\"write-write", "12"),
 ("no range validation", "mvcc.py", "                    if lo <= key < hi and s._last_commit_ts(key) > self.start_ts:", "                    if False:", "13"),
 ("async index applied immediately", "table.py", "    def _index_add(self, t: Txn, row: dict) -> None:\n        for col in self.indexes:\n            if col in row:\n                self.queue.append", "    def _index_add(self, t: Txn, row: dict) -> None:\n        return Table._index_add(self, t, row)\n        for col in self.indexes:\n            if col in row:\n                self.queue.append", "17"),
 ("key encoding is not prefix-free", "mvcc.py", "    return tag + raw.replace(b\"\\x00\", b\"\\x00\\xff\") + b\"\\x00\\x00\"", "    return tag + raw", "18"),
 ("btree version index drops tombstones", "mvcc.py", "        s._clock += 1\n        for key, value in self.writes.items():\n            s._put_version(key, s._clock, value)", "        s._clock += 1\n        for key, value in self.writes.items():\n            if value is not TOMBSTONE:\n                s._put_version(key, s._clock, value)", "18"),
 ("durable MVCC replays uncommitted versions", "mvcc.py", "        elif kind == \"commit\":\n            for enc_key, blob in pending.pop(tx, []):\n                out.append((enc_key, rec[\"ts\"], blob))\n    return out", "        elif kind == \"commit\":\n            for enc_key, blob in pending.pop(tx, []):\n                out.append((enc_key, rec[\"ts\"], blob))\n    for items in pending.values():\n        for enc_key, blob in items:\n            out.append((enc_key, 0, blob))\n    return out", "19"),
]
