"""Hints for .claude/skills/graded-module/scripts/make_templates.py."""
HINTS = {
 "network.py": {
  "Network.__init__": "Store the seed, delays, drop rate and reorder flag; make your own random.Random(seed); start now=0, an empty heap queue, an empty node registry, and no partition (None).",
  "Network.register": "Remember id -> node, so deliver_due can call node.receive().",
  "Network.crash": "Add the node id to the set of stopped nodes; it stops sending and receiving.",
  "Network.restart": "Remove the node id from the stopped set.",
  "Network.set_partition": "Store the groups as a list of sets; two nodes may talk only if some group contains both.",
  "Network.heal": "Forget the groups: everyone is connected again.",
  "Network._connected": "False if either endpoint is stopped. If there is no partition, True. Otherwise True only when one group contains both a and b.",
  "Network.send": "Drop the message if the endpoints are not connected, or if the drop roll fires. Pick a delay: the explicit one, else a seeded randint between min_delay and max_delay (add a spike when reorder is on). Push (now+delay, seq, src, dst, msg) so the heap orders by arrival time.",
  "Network.pending": "How many messages are still queued.",
  "Network.deliver_due": "Pop every message whose delivery time is <= now, in heap order, and hand it to its destination's receive(src, msg).",
  "Network.step": "Advance now by one and deliver everything due.",
 },
 "raft.py": {
  "RaftNode.__init__": "Set the stable state (current_term=0, voted_for=None, log=[]) and the volatile state (FOLLOWER, leader_id, commit_index=0, last_applied=0), plus next_index/match_index/votes_received and an empty applied list. Own a random.Random(seed). Start the election timer.",
  "RaftNode.majority": "One more than half the peers: len(self.peers)//2 + 1.",
  "RaftNode.last_log_index": "len(self.log).",
  "RaftNode.last_log_term": "The last entry's term, or 0 for an empty log.",
  "RaftNode.is_running": "Whether tick/receive should do anything (a crashed node is not running).",
  "RaftNode._reset_election_timer": "Set the election deadline to now + rng.randint(lo, hi). The randomisation is what stops every node timing out together.",
  "RaftNode._reset_heartbeat_timer": "Set the heartbeat deadline to now + heartbeat_interval.",
  "RaftNode.stop": "A crash: mark the node not running. Stable storage (term, vote, log) is kept.",
  "RaftNode.start": "Come back as a follower with no known leader, clear the per-peer leader state, and reset the election timer.",
  "RaftNode.tick": "If leader: send heartbeats and reset the heartbeat timer when its deadline passes. Otherwise: if now is past the election deadline, start an election.",
  "RaftNode.receive": "Dispatch by msg['type'] to the four handlers.",
  "RaftNode._start_election": "Become CANDIDATE, current_term += 1, vote for yourself, reset the timer, and send RequestVote (with your last log index and term) to every peer. If you already have a majority (a one-node cluster), become leader.",
  "RaftNode._on_request_vote": "A higher term makes you a follower and clears your vote. If the term matches and you have not voted for someone else and the candidate's log is at least as up to date (last_log_term, then last_log_index), grant the vote, remember it, and reset your timer. Reply with your term and the decision.",
  "RaftNode._on_request_vote_reply": "A higher term makes you a follower. If you are still a candidate in that term and the vote was granted, count it; on a majority become leader.",
  "RaftNode._become_leader": "Set state LEADER, leader_id to yourself, next_index[p]=last_log_index+1 and match_index[p]=0 for every peer, then broadcast an (empty) AppendEntries at once to assert leadership.",
  "RaftNode._broadcast_append": "Send an AppendEntries to every peer except yourself.",
  "RaftNode._send_append": "For this peer: prev = next_index-1, prev_term = that entry's term (0 if none), entries = your log from prev onward, leader_commit = commit_index. Include term and leader id.",
  "RaftNode._on_append_entries": "Reject a lower term. A higher term makes you a follower. Reset your election timer and note the leader. If prev_log_index is past your log or its term does not match, reject with a conflict_index pointing at the first entry of the disagreeing term. Otherwise keep the matching prefix, DELETE the conflicting suffix, extend with the new entries, then set commit_index = min(leader_commit, prev_log_index + len(entries)) and apply. Reply success with match_index.",
  "RaftNode._on_append_entries_reply": "A higher term makes you a follower. Ignore replies unless you are still the leader of that term. Success: raise match_index/next_index for that peer and try to advance the commit. Failure: back next_index up (use conflict_index to skip a whole term) and resend.",
  "RaftNode._advance_commit": "Scan N downward from the last log index: skip entries whose term is not the current term (Figure 8), and commit the first N that is held by a majority (yourself plus the peers with match_index >= N). Then apply.",
  "RaftNode._apply": "While last_applied < commit_index: advance it and append (index, term, command) to self.applied. In-order and exactly once follows from walking the index up one at a time.",
  "RaftNode.propose": "Refuse unless you are the leader. Append an entry stamped with the current term, replicate it, and return its index.",
  "Cluster.__init__": "Build ids n0..n(n-1), one Network (seeded), and one RaftNode per id wired to it; give each node a distinct seed so their timeouts differ.",
  "Cluster.run": "For each tick: step the network, then tick every node in id order. Order matters for reproducibility.",
  "Cluster.leaders": "Every running node whose state is LEADER.",
  "Cluster.leader": "The single leader, or None when there is no leader or more than one.",
  "Cluster.crash": "Stop the node and tell the network to drop its messages.",
  "Cluster.restart": "Start the node and tell the network it is reachable again.",
  "Cluster.partition": "Pass the groups to the network so cross-group messages are dropped.",
  "Cluster.heal": "Remove the partition.",
  "Cluster.propose": "Send the command to the current leader; None if there is no unique leader.",
  "Cluster.applied_conflict": "For every (index, command) in every node's applied history, the same index must carry the same command everywhere. Return the first disagreement.",
  "Cluster.committed_conflict": "For every index up to each node's commit_index, the (term, command) must be identical across nodes. Return the first disagreement.",
  "Cluster.log_matching_violation": "For every pair of logs, wherever they share a term at some index every earlier entry must be identical. Return the first violation.",
 },
}
