"""Planted bugs for .claude/skills/graded-module/scripts/mutate.py."""
MUTATIONS = [
  ("G-Counter merge sums instead of taking the max", "gc_counter.py",
   "            out.counts[name] = max(self.counts.get(name, 0), other.counts.get(name, 0))",
   "            out.counts[name] = self.counts.get(name, 0) + other.counts.get(name, 0)",
   "1"),
  ("PN counter decrement increments the positive side", "gc_counter.py",
   "        self._n.increment(by)",
   "        self._p.increment(by)",
   "2"),
  ("LWW tie-break compares only the timestamp, so ties are order-dependent", "lww_register.py",
   "        if (other._ts, other._writer) > (self._ts, self._writer):",
   "        if other._ts > self._ts:",
   "4"),
  ("OR-set remove deletes the observed tags instead of tombstoning them", "or_set.py",
   "        for tag in self._adds.get(element, ()):\n            self._removed.add(tag)",
   "        self._adds.pop(element, None)",
   "6"),
  ("OR-set tag is not unique, so a re-add collides with the old tombstone", "or_set.py",
   "        self._clock += 1\n        return (self.node, self._clock)",
   "        self._clock += 1\n        return (self.node,)",
   "5"),
  ("OR-set merge keeps only its own tombstones (merge not commutative)", "or_set.py",
   "        out._removed = set(self._removed) | set(other._removed)",
   "        out._removed = set(self._removed)",
   "7"),
]
